name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:  # Manual run support

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: danilosilva0
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output  # The branch the action should deploy to
          folder: dist    # The folder the action should deploy
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
